### PR TITLE
Remove extraneous packages from requirments.txt

### PR DESCRIPTION
**Pull request by Victoradukwu**
**What does this PR do?**

* Remove extraneous requirements from from `requirements.txt` 

**Description of Task to be completed?**

* delete `django` and `pillow` as requirements
**How should this be manually tested?**
* pull the branch `update-requirements-txt` and checkout to the branch
* open the requirements.txt file. You will find that django and pillow are no longer there
**Any background context you want to provide?**

**What are the relevant pivotal tracker stories?**

### CODE REVIEW

**Comment by Victoradukwu** [comment]
@Maxcutex `Pandas` is used in the code. Removing it will break the code. `Numpy`, I did not add that and I do not know where it is used in the code. Removing it might break the application if it is used anywhere in the codebase. Do you still insist I remove them?

**Comment by Maxcutex** [comment]
can you show me where they are used?

**Comment by Victoradukwu** [comment]
@Maxcutex  Pandas is used in `reports_controller` module. lines 4 and 26.

**Comment by Maxcutex** [comment]
ok

**Pull request merged**
